project:
  type: book
book:
  title: Quizzes with Webexercises and Quarto BAnderson

  author: Brenda Anderson
  date: 11/20/2023
  chapters:
  - index.qmd
  - intro.qmd
  - Webexercisetest.Rmd
  - summary.qmd
  - references.qmd
bibliography: references.bib
format:
  html:
    execute:
      echo: false
    theme: cosmo
    css: include/webex.css
    include-after-body: include/webex.js
    # code-fold: false
    # code-summary: Show the code
    # code-tools: true
  pdf:
    documentclass: scrreprt
draft: false
categories:
- Quarto
- Webexercises
- Teaching
editor: visual
